@ExpenseLoggerApi_HostAddress = http://localhost:5001

GET {{ExpenseLoggerApi_HostAddress}}/todos/
Accept: application/json

###

GET {{ExpenseLoggerApi_HostAddress}}/todos/1
Accept: application/json

###
